# Generated by Django 2.2 on 2019-05-09 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_2020', '0002_auto_20190123_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulee',
            old_name='nyt_district',
            new_name='cnn_district',
        ),
    ]
